---
- name: Apply TrackPoint responsiveness settings
  copy: src=rc.local dest=/etc/rc.local
  tags:
    - thinkpad

- name: Apply TrackPoint button emulation settings
  copy: src=.xsessionrc dest=/home/{{ user }}/.xsessionrc owner={{ user }} group={{ user }}
  tags:
    - thinkpad

- name: Make WiFi WiFast
  lineinfile:
    dest: /etc/modprobe.d/iwlwifi-opt.conf
    regexp: "^options iwlwifi"
    line: "options iwlwifi 11n_disable=1 power_save=0 swcrypto=1"
    create: yes
  tags:
    - network

- name: Disable IPV6
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: "^{{ item }}"
    line: "{{ item }}"
    create: yes
  with_items:
    - net.ipv6.conf.all.disable_ipv6 = 1
    - net.ipv6.conf.default.disable_ipv6 = 1
    - net.ipv6.conf.lo.disable_ipv6 = 1
  tags:
    - network

- name: Create Windows mount
  file: path=/mnt/windows state=directory owner={{ user }}
  tags:
    - filesystem

- name: Add Windows mount to the fstab
  lineinfile:
    dest: /etc/fstab
    regexp: ^UUID=607202BF72029A44
    line: UUID=607202BF72029A44       /mnt/windows            ntfs-3g defaults,windows_names,locale_en_US.utf8,rw,user,auto,fmask=0177,dmask=0077,uid=1000,discard,noatime,nofail    0   0
  register: fstab_updated
  tags:
    - filesystem

- name: Verify mounts
  command: mount -a
  tags:
    - filesystem

- name: Install ThinkPad-related packages
  apt: pkg={{ item }}
  with_items:
    - tp-smapi-dkms
    - acpi-call-dkms
  tags:
    - thinkpad

- name: Download Dropbox
  get_url: url=https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.10.28_amd64.deb dest=/tmp/
  tags:
    - dropbox

- name: Install Dropbox dependencies
  apt: pkg=python-gpgme
  tags:
    - dropbox

- name: Install Dropbox
  apt: deb=/tmp/dropbox_2015.10.28_amd64.deb
  tags:
    - dropbox
