---
- name: Enable i915 early load
  become: yes
  lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: '^MODULES='
    line: 'MODULES=(i915)'

- name: Set i915 guc to load
  become: yes
  lineinfile:
    path: /etc/modprobe.d/i915.conf
    create: yes
    line: 'options i915 enable_guc=2'

- name: Apply TrackPoint responsiveness settings
  become: yes
  copy: src=rc.local dest=/opt/configure-trackpoint.sh
  tags:
    - thinkpad

- name: Deploy TrackPoint service
  become: yes
  copy: src=trackpoint.service dest=/etc/systemd/system/trackpoint.service
  tags:
    - thinkpad

- name: Install TrackPoint service
  become: yes
  systemd: name=trackpoint state=started daemon_reload=yes
  tags:
    - thinkpad

- name: Apply TrackPoint button emulation settings
  copy: src=.xsessionrc dest=/home/{{ user }}/.xsessionrc owner={{ user }} group={{ user }}
  tags:
    - thinkpad

- name: Make WiFi WiFast
  become: yes
  lineinfile:
    dest: /etc/modprobe.d/iwlwifi-opt.conf
    regexp: "^options iwlwifi"
    line: "options iwlwifi 11n_disable=1 power_save=0 swcrypto=1"
    create: yes
  tags:
    - network

- name: Disable IPV6
  become: yes
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: "^{{ item }}"
    line: "{{ item }}"
    create: yes
  with_items:
    - net.ipv6.conf.all.disable_ipv6 = 1
    - net.ipv6.conf.default.disable_ipv6 = 1
    - net.ipv6.conf.lo.disable_ipv6 = 1
  tags:
    - network

- name: Create Windows mount
  become: yes
  file: path=/mnt/windows state=directory owner={{ user }}
  tags:
    - filesystem

- name: Add Windows mount to the fstab
  become: yes
  lineinfile:
    dest: /etc/fstab
    regexp: ^UUID=607202BF72029A44
    line: UUID=607202BF72029A44       /mnt/windows            ntfs-3g defaults,windows_names,locale_en_US.utf8,rw,user,auto,fmask=0177,dmask=0077,uid=1000,discard,noatime,nofail    0   0
  register: fstab_updated
  tags:
    - filesystem

- name: Verify mounts
  become: yes
  command: mount -a
  tags:
    - filesystem

- name: Install ThinkPad-related packages
  become: yes
  pacman: pkg={{ item }}
  with_items:
    - tpacpi-bat
    - acpi_call-dkms
  tags:
    - thinkpad
