---
# This playbook provisions Ananke

- name: apply common configuration to all nodes
  hosts: localhost
  connection: local
  user: aru
  sudo: true
  vars:
    user: aru
    code_dir: /home/aru/code
  roles:
    - dotfiles
    - { role: linux, tags: [linux] }
    - { role: dropbox, tags: [dropbox] }
    - { role: opera, tags: [opera] }
    - { role: ananke, tags: [ananke] }
    - development
    - vim
