---
# This playbook provisions all of the computer

- name: apply common configuration to all nodes
  hosts: localhost
  connection: local
  user: aru
  become: yes
  become_method: sudo
  vars:
    user: aru
    code_dir: /home/aru/code
    hidpi: yes
    hidpi_scale: 1.3
  roles:
    - dotfiles
    - { role: linux, tags: [linux] }
    - { role: dropbox, tags: [dropbox] }
    - { role: opera, tags: [opera] }
    - { role: juventas, tags: [juventas] }
    - { role: development, tags: [development] }
    - vim
