---
- name: Install Arch packages
  become: true
  pacman: pkg={{ item }}
  with_items:
    - obs-studio
    - fprintd
    - kdenlive
    - plasma-browser-integration
    - calibre

- name: Install AUR packages
  yay: name={{ item }} state=present
  with_items:
    - zoom
    - v4l2ucp
    - 1password
    - beeper-latest-bin
    - discord
    - qflipper
    - brother-hll2350dw

- name: Enable bluetooth
  become: true
  systemd: name=bluetooth.service state=started enabled=true

- name: Enable CUPS
  become: true
  systemd: name=cups.service state=started enabled=true

- name: Configure wireless regulatory domain
  become: true
  lineinfile:
    path: /etc/conf.d/wireless-regdom
    line: 'WIRELESS_REGDOM="US"'
