---
- name: check for yay
  stat:
    path: /usr/bin/yay
  register: yay_exec

- name: Create AUR build user
  become: true
  user:
    name: aur_builder
    group: wheel
  when: not yay_exec.stat.exists

- name: Set AUR sudo privileges
  become: true
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'
  when: not yay_exec.stat.exists

- name: Install yay
  become: true
  become_user: aur_builder
  kewlfft.aur.aur: name=yay state=present
  when: not yay_exec.stat.exists

- name: Install base items
  become: true
  pacman:
    name:
      - yakuake
      - zsh
      - tlp
      - smartmontools
      - ethtool
      - htop
      - ncdu
      - audacity
      - elinks
      - gimp
      - imagemagick
      - lame
      - libjpeg-turbo
      - libjpeg6-turbo
      - libpng
      - libxml2
      - libxslt
      - unrar
      - unzip
      - vlc
      - ca-certificates
      - curl
      - exfatprogs
      - acpi_call-dkms
      - firefox-developer-edition
      - wezterm
      - wezterm-terminfo
      - wezterm-shell-integration

- name: Deploy zshrc
  file: src="{{ code_dir }}/dotfiles/{{ item }}" dest="/home/{{ user }}/.{{ item }}" state=link force=true
  with_items:
    - zsh
    - zshrc

- name: Set zshell
  become: true
  user: name="{{ user }}" shell=/usr/bin/zsh

- name: Deploy .dircolors
  file: src="{{ code_dir }}/dotfiles/dircolors" dest=/home/{{ user }}/.dircolors state=link

- name: Install Chrome beta
  become: true
  pacman: name=google-chrome-beta state=present executable=yay extra_args="--builddir /var/cache/yay"

- name: Force HiDPI Chrome
  become: true
  lineinfile:
    dest: /usr/share/applications/google-chrome-beta.desktop
    regexp: Exec=/usr/bin/google-chrome-beta %U
    line: Exec=/usr/bin/google-chrome-beta %U --force-device-scale-factor={{ hidpi_scale }}
  when: hidpi | bool
  tags:
    - hidpi

- name: Make certs directory
  file: path=/home/{{ user }}/certs state=directory owner={{ user }} group={{ user }}

- name: Install fonts
  become: true
  pacman:
    name:
      - ttf-dejavu
      - ttf-droid
      - ttf-roboto
      - ttf-ubuntu-font-family
      - ttf-bitstream-vera
      - wqy-microhei
      - adobe-source-code-pro-fonts
  tags:
    - fonts
