---
- name: Install base items
  apt: name={{ item }}
  with_items:
    - yakuake
    - choqok
    - zsh

- name: Deploy zshrc
  file: src="{{ code_dir }}/dotfiles/zshrc" dest=/home/{{ user }}/.zshrc state=link

- name: Set zshell
  user: name=aru shell=/usr/bin/zsh

- name: Deploy .dircolors
  file: src="{{ code_dir }}/dotfiles/dircolors" dest=/home/{{ user }}/.dircolors state=link

- name: Install Google signing key
  shell: wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -

- name: Add Chrome source
  apt_repository: repo="deb http://dl.google.com/linux/chrome/deb/ stable main" state=present

- name: Check if Chrome is installed
  command: dpkg-query -l google-chrome-beta
  register: chrome_is_installed
  failed_when: chrome_is_installed.rc > 1
  changed_when: no

- name: Install Chrome beta
  apt: name=google-chrome-beta update_cache=yes
  when: chrome_is_installed.rc == 0

- name: Install Opera signing key
  shell: wget -q -O - http://deb.opera.com/archive.key | apt-key add -

- name: Add Opera source
  apt_repository: repo="deb http://deb.opera.com/opera/ stable non-free" state=present

- name: Check if Opera is installed
  command: dpkg-query -l opera
  register: opera_is_installed
  failed_when: opera_is_installed.rc > 1
  changed_when: no

- name: Install Opera
  apt: name=opera update_cache=yes
  when: opera_is_installed.rc == 0

- name: Make certs directory
  file: path=/home/{{ user }}/certs state=directory owner={{ user }} group={{ user }}
