---
- name: Install base items
  apt: name={{ item }}
  with_items:
    - yakuake
    - choqok
    - zsh
    - tlp
    - smartmontools
    - ethtool
    - htop
    - ncdu
    - audacity
    - elinks
    - gimp
    - imagemagick
    - kubuntu-restricted-extras
    - kubuntu-restricted-addons
    - lame
    - libjpeg-dev
    - libjpeg8-dev
    - libpng12-dev
    - unrar
    - unzip
    - vlc

- name: Check if Dropbox is installed
  command: dpkg-query -l dropbox
  register: dropbox_is_installed
  failed_when: dropbox_is_installed.rc >= 1
  changed_when: no

- name: Download Dropbox
  get_url: url=https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.10.28_amd64.deb dest=/tmp/
  when: dropbox_is_installed.rc >=1
  tags:
    - dropbox

- name: Install Dropbox dependencies
  apt: pkg=python-gpgme
  when: dropbox_is_installed.rc >=1
  tags:
    - dropbox

- name: Install Dropbox
  apt: deb=/tmp/dropbox_2015.10.28_amd64.deb
  when: dropbox_is_installed.rc >=1
  tags:
    - dropbox

- name: Uninstall useless items
  apt: name={{ item }} state=absent
  with_items:
    - myspell-en-au
    - myspell-en-gb
    - myspell-en-za
    - hunspell-en-ca

- name: Deploy zshrc
  become: no
  file: src="{{ code_dir }}/dotfiles/zshrc" dest=/home/{{ user }}/.zshrc state=link

- name: Set zshell
  become: no
  user: name=aru shell=/usr/bin/zsh

- name: Deploy .dircolors
  become: no
  file: src="{{ code_dir }}/dotfiles/dircolors" dest=/home/{{ user }}/.dircolors state=link

- name: Add Kubuntu backports
  apt_repository: repo=ppa:kubuntu-ppa/backports
  tags:
    - kde

- name: Install Google signing key
  shell: wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -

- name: Add Chrome source
  apt_repository: repo="deb http://dl.google.com/linux/chrome/deb/ stable main" state=present

- name: Check if Chrome is installed
  command: dpkg-query -l google-chrome-beta
  register: chrome_is_installed
  failed_when: chrome_is_installed.rc > 1
  changed_when: no

- name: Install Chrome beta
  apt: name=google-chrome-beta update_cache=yes
  when: chrome_is_installed.rc != 0

- name: Force HiDPI Chrome
  lineinfile:
    dest: /usr/share/applications/google-chrome-beta.desktop
    regexp: Exec=/usr/bin/google-chrome-beta %U
    line: Exec=/usr/bin/google-chrome-beta %U --force-device-scale-factor=1.3
  when: hidpi

- name: Install Opera signing key
  shell: wget -q -O - http://deb.opera.com/archive.key | apt-key add -

- name: Add Opera source
  apt_repository: repo="deb http://deb.opera.com/opera/ stable non-free" state=present

- name: Check if Opera is installed
  command: dpkg-query -l opera
  register: opera_is_installed
  failed_when: opera_is_installed.rc > 1
  changed_when: no

- name: Install Opera
  apt: name=opera update_cache=yes
  when: opera_is_installed.rc != 0

- name: Make certs directory
  become: no
  file: path=/home/{{ user }}/certs state=directory owner={{ user }} group={{ user }}

- name: Accept MS Core Fonts license
  debconf: name='ttf-mscorefonts-installer' quetion='msttcorefonts/accepted-mscorefonts-eula' value='true' vtype='select'
  tags:
    - fonts

- name: Install fonts
  apt: name={{ item }}
  with_items:
  - fonts-dejavu
  - fonts-dejavu-core
  - fonts-dejavu-extra
  - fonts-droid-fallback
  - fonts-font-awesome
  - fonts-freefont-ttf
  - fonts-kacst
  - fonts-kacst-one
  - fonts-liberation
  - fonts-lmodern
  - fonts-lyx
  - fonts-mathjax
  - fonts-nanum
  - fonts-opensymbol
  - fonts-oxygen
  - fonts-roboto
  - fonts-unfonts-core
  - ttf-ancient-fonts
  - ttf-ancient-fonts-symbola
  - ttf-bitstream-vera
  - ttf-dejavu
  - ttf-dejavu-core
  - ttf-dejavu-extra
  - ttf-liberation
  - ttf-mscorefonts-installer
  - ttf-oxygen-font-family
  - ttf-ubuntu-font-family
  - ttf-unfonts-core
  - ttf-wqy-microhei
  - ttf-xfree86-nonfree
  tags:
    - fonts

- name: Download Source Code Pro
  become: no
  get_url: url=https://github.com/adobe-fonts/source-code-pro/archive/2.010R-ro/1.030R-it.tar.gz dest=/tmp/
  tags:
    - fonts

- name: Uncompress package
  become: no
  unarchive: src=/tmp/1.030R-it.tar.gz dest=/tmp/
  tags:
    - fonts

- name: Create fonts directory
  become: no
  file: path=/home/{{ user }}/.fonts state=directory
  tags:
    - fonts

- name: Copy fonts over
  become: no
  shell: cp /tmp/source-code-pro-2.010R-ro-1.030R-it/OTF/*.otf /home/{{ user }}/.fonts/
  tags:
    - fonts

- name: generate font cache
  command: fc-cache -f -v
  tags:
    - fonts

- name: Add autostart applications
  become: no
  copy: src={{ item }}.desktop dest=/home/{{ user }}/.config/autostart/
  with_items:
    - yakuake
    - choqok
    - dropbox
  tags:
    - dropbox
