---
- name: Create local bin directory
  file: path=/home/{{ user }}/bin state=directory

- name: Enable hibernation
  become: yes
  copy: src=com.ubuntu.enable-hibernate.pkla dest=/etc/polkit-1/localauthority/50-local.d/com.ubuntu.enable-hibernate.pkla
  tags:
    - power

- name: Install NFS packages
  become: yes
  apt: pkg=nfs-common state=present
  tags:
    - filesystem

- name: Tune swappiness
  become: yes
  sysctl: name=vm.swappiness value=1 state=present
  tags:
    - filesystem

- name: Generate HiDPI Grub font
  become: yes
  command: "grub-mkfont --output=/boot/grub/fonts/DejaVuSansMono24.pf2 --size=24 /usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
  args:
    creates: /boot/grub/fonts/DejaVuSansMono24.pf2
  notify: update grub
  when: hidpi
  tags:
    - hidpi

- name: Set suspend behavior
  become: yes
  lineinfile:
    dest: /etc/default/grub
    firstmatch: yes
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash mem_sleep_default=deep"'
  notify: update grub

- name: Disable akonadi
  lineinfile:
    dest: ~/.config/akonadi/akonadiserverrc
    create: yes
    regexp: StartServer=
    line: StartServer=false
  tags:
    - kde

- name: Make plasma use KDE scaling
  lineinfile:
    dest: ~/.config/plasma-workspace/env/plasma.sh
    create: yes
    line: export PLASMA_USE_QT_SCALING=1
  when: hidpi
  tags:
    - kde
    - hidpi
    - kde-hidpi

- name: Add Arc theme repo
  become: yes
  apt_repository:
    repo: 'ppa:papirus/papirus'
  tags:
    - kde

- name: Install Arc theme
  become: yes
  apt: pkg=arc-kde install_recommends=yes
  tags:
    - kde

- name: Install konsole colorscheme
  get_url:
    url: https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/konsole/Broadcast.colorscheme
    dest: ~/.local/share/konsole/Broadcast.colorscheme
  tags:
    - kde

- name: Install emoji keyboard prereqs
  become: yes
  apt: pkg={{ item }} state=present
  with_items:
    - python3-gi
    - gir1.2-gtk-3.0
    - gir1.2-glib-2.0
    - python3-evdev
    - gir1.2-appindicator3-0.1

- name: Install emoji keyboard
  pip:
    name: '{{ item }}'
    virtualenv: /home/{{ user }}/.virtualenvs/emoji-keyboard
    virtualenv_site_packages: yes
    virtualenv_python: python3
  with_items:
    - python-xlib
    - https://github.com/OzymandiasTheGreat/emoji-keyboard/archive/master.zip

- name: Link emoji keyboard
  file: src=/home/{{ user }}/.virtualenvs/emoji-keyboard/bin/emoji-keyboard dest=/home/{{ user }}/bin/emoji-keyboard state=link

- name: Make emoji keyboard autostart
  copy: src=emoji-keyboard.desktop dest=~/.config/autostart/
