---
- name: Deploy gitconfig
  become: true
  file: src="{{ code_dir }}/dotfiles/gitconfig" dest=/home/{{ user }}/.gitconfig state=link

- name: Deploy gitignore
  become: true
  file: src="{{ code_dir }}/dotfiles/gitignore_global" dest=/home/{{ user }}/.gitignore_global state=link

- name: Deploy Ack settings
  become: true
  file: src="{{ code_dir }}/dotfiles/ackrc" dest=/home/{{ user }}/.ackrc state=link

- name: Deploy pylintrc
  become: true
  file: src="{{ code_dir }}/dotfiles/pylintrc" dest=/home/{{ user }}/.pylintrc state=link
  tags:
    - python

- name: Install dev tools
  become: true
  pacman:
    name:
    - direnv
    - jq
    - ripgrep
    - git-delta
    - bat
    - xh
    - pgcli

- name: Install AUR dev tools
  become: true
  become_user: "{{ user }}"
  yay:
    name:
      - asdf-vm
      - git-req
    state: present

- name: Install base Python packages
  become: true
  pacman:
    name:
      - tk
      - python
      - python3
      - python-virtualenvwrapper
      - python-pip
      - python-pipx
      - python-poetry
  tags:
    - python

- name: Remove conflicting rust packages
  become: true
  pacman:
    name:
      - rust
    state: absent
  tags:
    - rust

- name: Install base rust packages
  become: true
  pacman:
    name:
      - rustup
  tags:
    - rust

- name: Create virtualenv directory
  file: path=/home/{{ user }}/.virtualenvs state=directory
  tags:
    - python

- name: Deploy virtualenv postactivate config
  command: cp /home/{{ user }}/code/dotfiles/virtualenv/postactivate /home/{{ user }}/.virtualenvs/ creates=/home/{{ user }}/.virtualenvs/postactivate
  tags:
    - python

- name: Deploy virtualenv postdeactivate config
  command: cp /home/{{ user }}/code/dotfiles/virtualenv/postdeactivate /home/{{ user }}/.virtualenvs/  creates=/home/{{ user }}/.virtualenvs/postdeactivate
  tags:
    - python

- name: Install CSV utils
  become: true
  community.general.pipx: name={{ item }}
  with_items:
    - csvkit
    - xlsx2csv
  tags:
    - python

- name: Create bin directory
  file: path=/home/{{ user }}/bin state=directory

- name: Install miscellaneous utils
  become: true
  community.general.pipx: name={{ item }}
  with_items:
    - grip
    - restview
  tags:
    - webdev
    - python

# - name: Install Node stuff
#   become: true
#   pacman:
#     name:
#       - nodejs-lts-hydrogen
#       - npm
#   tags:
#     - javascript
#     - webdev

- name: Install virtualization tools
  become: true
  pacman:
    name:
      - virtualbox
      - virtualbox-host-dkms
      - vagrant
      - docker
      - docker-compose
  tags:
    - vagrant
    - docker

- name: Add docker group
  become: true
  group:
    name: docker
    state: present
  tags:
    - docker

- name: Add user to Docker group
  become: true
  user:
    name: "{{ user }}"
    append: yes
    groups: docker
  tags:
    - docker

- name: Symlink WezTerm config
  file: src="{{ code_dir }}/dotfiles/wezterm" dest=/home/{{ user }}/.config/wezterm state=link

- name: Install internet devtools
  become: true
  pacman:
    name:
      - aws-cli
