---
- name: Deploy gitconfig
  become: no
  file: src="{{ code_dir }}/dotfiles/gitconfig" dest=/home/{{ user }}/.gitconfig state=link

- name: Deploy Ack settings
  become: no
  file: src="{{ code_dir }}/dotfiles/ackrc" dest=/home/{{ user }}/.ackrc state=link

- name: Deploy pylintrc
  become: no
  file: src="{{ code_dir }}/dotfiles/pylintrc" dest=/home/{{ user }}/.pylintrc state=link
  tags:
    - python

- name: Install dev tools
  become: yes
  pacman:
    name:
    - jq
    - ripgrep

- name: Install base Python packages
  become: yes
  pacman:
    name:
      - python
      - python3
      - python-virtualenvwrapper
      - python-pipx
  tags:
    - python

- name: Create virtualenv directory
  become: no
  file: path=/home/{{ user }}/.virtualenvs state=directory
  tags:
    - python

- name: Deploy virtualenv postactivate config
  become: no
  command: cp /home/{{ user }}/code/dotfiles/virtualenv/postactivate /home/{{ user }}/.virtualenvs/ creates=/home/{{ user }}/.virtualenvs/postactivate
  tags:
    - python

- name: Deploy virtualenv postdeactivate config
  become: no
  command: cp /home/{{ user }}/code/dotfiles/virtualenv/postdeactivate /home/{{ user }}/.virtualenvs/  creates=/home/{{ user }}/.virtualenvs/postdeactivate
  tags:
    - python

- name: Install CSV utils
  become: no
  community.general.pipx: name={{ item }}
  with_items:
    - csvkit
    - xlsx2csv
  tags:
    - python

- name: Create bin directory
  file: path=/home/{{ user }}/bin state=directory

- name: Install miscellaneous utils
  become: no
  community.general.pipx: name={{ item }}
  with_items:
    - grip
    - restview
    - httpie
  tags:
    - webdev
    - python

- name: Install Node stuff
  become: yes
  pacman:
    name:
      - nodejs-lts-gallium
      - npm
  tags:
    - javascript
    - webdev

- name: Install virtualization tools
  become: yes
  pacman:
    name:
      - virtualbox
      - virtualbox-host-dkms
      - vagrant
      - docker
  tags:
    - vagrant
    - docker

- name: Add docker group
  become: yes
  group:
    name: docker
    state: present
  tags:
    - docker

- name: Add user to Docker group
  become: yes
  user:
    name: "{{ user }}"
    append: yes
    groups: docker
  tags:
    - docker
