---
- name: Install Dropbox
  become: yes
  become_user: aur_builder
  aur: name=dropbox skip_installed=true

- name: Set autostart
  copy: src=dropbox.desktop dest=/home/{{ user }}/.config/autostart/
