---
- name: Install deps
  become: true
  pacman:
    name:
      - autoconf
      - automake
      - pkgconf
      - luarocks
      - python-pynvim
      # Needed for clipboard access on X11 systems
      - xclip
      - xsel
      # Needed for clipboard access on Wayland systems
      - wl-clipboard

- name: Install 3rd party deps
  become: true
  yay:
    name:
      - uctags-git

- name: Install NeoVim
  become: true
  pacman: name=neovim
  notify: Install NeoVim python packages

- name: Symlink Vim configuration
  file: src="{{ code_dir }}/dotfiles/vimrc" dest=/home/{{ user }}/.vimrc state=link

- name: Create Neovim config directory
  file: path=/home/{{ user }}/.config/nvim state=directory

- name: Symlink NeoVim configuration
  file: src="{{ code_dir }}/dotfiles/nvim/{{ item }}" dest=/home/{{ user }}/.config/nvim/{{ item }} state=link
  with_items:
    - init.lua
    - lazy-lock.json
    - lua
    - after
