---
- name: Install deps
  become: yes
  pacman:
    name:
      - autoconf
      - automake
      - pkgconf
      - xclip
      - xsel

- name: Install some deps
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - uctags-git
    
- name: Install NeoVim
  become: yes
  pacman: name=neovim
  notify: Install NeoVim python packages

- name: Symlink Vim configuration
  file: src="{{ code_dir }}/dotfiles/vimrc" dest=/home/{{ user }}/.vimrc state=link

- name: Create Neovim config directory
  file: path=/home/{{ user }}/.config/nvim state=directory

- name: Symlink NeoVim configuration
  file: src="{{ code_dir }}/dotfiles/vimrc" dest=/home/{{ user }}/.config/nvim/init.vim state=link
