---
- name: Install deps
  become: true
  pacman:
    name:
      - autoconf
      - automake
      - pkgconf
      - xclip
      - xsel

- name: Install some deps
  become: true
  pacman:
    name:
      - uctags-git
    executable: yay
    extra_args: "--builddir /var/cache/yay"

- name: Install NeoVim
  become: true
  pacman: name=neovim
  notify: Install NeoVim python packages

- name: Symlink Vim configuration
  file: src="{{ code_dir }}/dotfiles/vimrc" dest=/home/{{ user }}/.vimrc state=link

- name: Create Neovim config directory
  file: path=/home/{{ user }}/.config/nvim state=directory

- name: Symlink NeoVim configuration
  file: src="{{ code_dir }}/dotfiles/nvim/{{ item }}" dest=/home/{{ user }}/.config/nvim/{{ item }} state=link
  with_items:
    - init.lua
    - coc-settings.json
    - lazy-lock.json
    - lua
    - after
