---
- name: Install vim
  become: yes
  apt: name={{ item }}
  with_items:
    - curl
    - vim-gtk
    - git
    - exuberant-ctags
    - python-dev
    - python-pip
    - python3-dev
    - python3-pip
    - xsel

- name: Add NeoVim PPA
  become: yes
  apt_repository: repo="ppa:neovim-ppa/unstable"

- name: Install NeoVim
  become: yes
  apt: pkg=neovim
  notify: install NeoVim python packages

- name: Symlink Vim configuration
  file: src="{{ code_dir }}/dotfiles/vimrc" dest=/home/{{ user }}/.vimrc state=link

- name: Create Neovim config directory
  file: path=/home/{{ user }}/.config/nvim state=directory

- name: Symlink NeoVim configuration
  file: src="{{ code_dir }}/dotfiles/vimrc" dest=/home/{{ user }}/.config/nvim/init.vim state=link

- name: Install Powerline fonts
  command: ./powerline-setup.sh creates=/home/{{ user }}/.config/fontconfig/conf.d/10-powerline-symbols.conf
  args:
    chdir: "{{ code_dir }}/dotfiles"
