---
- name: Apply TrackPoint responsiveness settings
  copy: src=rc.local dest=/etc/rc.local mode=a+x
  tags:
    - thinkpad

- name: Set TrackPoint udev rule
  copy: src=10-trackpoint.rules dest=/etc/udev/rules.d/
  tags:
    - thinkpad

- name: Apply TrackPoint button emulation settings
  copy: src=.xsessionrc dest=/home/{{ user }}/.xsessionrc owner={{ user }} group={{ user }}
  tags:
    - thinkpad

- name: Deploy TouchPad disabling script
  copy: src=files/toggle-touchpad.sh dest=/home/{{ user }}/bin/toggle-touchpad.sh
  tags:
    - thinkpad

- name: Enable hibernation
  copy: src=com.ubuntu.enable-hibernate.pkla dest=/etc/polkit-1/localauthority/50-local.d/com.ubuntu.enable-hibernate.pkla
  tags:
    - power
    - thinkpad

- name: Disable xvideo rendering because Skylake
  copy: src=20-intel.conf dest=/usr/share/X11/xorg.conf.d/20-intel.conf
  tags:
    - thinkpad

- name: Create Windows mount
  file: path=/mnt/windows state=directory owner={{ user }}
  tags:
    - filesystem

- name: Install NFS packages
  apt: pkg=nfs-common state=present
  tags:
    - filesystem

- name: Create NAS mounts
  file: path=/storage/{{ item }} state=directory owner={{ user }}
  with_items:
    - backups
    - downloads
    - music
    - other
    - photo
    - video
  tags:
    - filesystem

- name: Get NAS IP
  command: dig +short alexandria
  register: nas_ip
  tags:
    - filesystem

- name: Mount the NAS shares
  mount:
    fstype: nfs
    name: /storage/{{ item }}
    src: "{{ nas_ip.stdout_lines[0] }}:/volume1/{{ item }}"
    state: mounted
  with_items:
    - backups
    - downloads
    - music
    - other
    - photo
    - video
  tags:
    - filesystem

- name: Nuke swappiness
  sysctl: name=vm.swappiness value=0 state=present
  tags:
    - filesystem

- name: Install ThinkPad-related packages
  apt: pkg={{ item }}
  with_items:
    - tp-smapi-dkms
    - acpi-call-dkms
  tags:
    - thinkpad

- name: Generate HiDPI Grub font
  command: "grub-mkfont --output=/boot/grub/fonts/DejaVuSansMono24.pf2 --size=24 /usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
  args:
    creates: /boot/grub/fonts/DejaVuSansMono24.pf2
  register: font_created
  when: hidpi
  tags:
    - hidpi

- name: Update Grub fonts
  command: update-grub
  when: font_created.changed
  tags:
    - hidpi

- name: Disable akonadi
  become: no
  lineinfile:
    dest: ~/.config/akonadi/akonadiserverrc
    regexp: StartServer=
    line: StartServer=false
  tags:
    - kde

- name: Set system tray icon sizes
  lineinfile:
    dest: /usr/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/config/main.xml
    regexp: <default>1</default>
    line: <default>2</default>
  when: hidpi
  tags:
    - kde
    - hidpi
    - kde-hidpi

